services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: wordle

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://mongo:27017/wordle
      REDIS_URL: redis://redis:6379
      ACCESS_TOKEN_SECRET: BAVR93rhroZ82SZAlDtUMlR6KJnJhVB93KdVy2lwruZ
      REFRESH_TOKEN_SECRET: z8qWw0VigCeVoLXTwaxif4leYtOkWQ9ZBtXtYv534b9
      CORS_ORIGIN: http://localhost:80

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:3000/api
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
